const express = require("express");
const router = express.Router();
const coupon = require("../controllers/couponController");
const handleCoupon = require("../controllers/couponRedeemController");
const fetchOrders = require("../controllers/fetchOrderController");
const fetchCoupons = require("../controllers/fetchCouponController");

//Generate Coupons
router.route("/coupon-gen").post(coupon.coupon_gen);
router.route("/coupon-list").get(coupon.coupon_list);
router.route("/verify").post(handleCoupon.verifyCoupon);
router.route("/confirm").post(handleCoupon.confirmCoupon);
router.route("/setRedemptionLimit").post(handleCoupon.setRedemptionLimit);

//Fetching Details
//Fetch Orders
router.route("/fetchOrders").post(fetchOrders.getOrderList);
//Fetch Coupons of respective order
router.route("/fetchCoupons").get(fetchCoupons.getCouponList);
//Fetch Recent Orders
router.route("/fetchRecentOrders").post(fetchOrders.getRecentOrderList);

//Fetch Total Coupons generated by user
router.route("/fetchUserCoupons").post(fetchCoupons.getUserCouponList);
//Fetch Redeemed Coupons
router
  .route("/fetchRedeemedCouponsCount")
  .post(fetchCoupons.getRedeemedCouponsCount);

// get static and dynamic coupons count
router
  .route("/fetchStaticDynamicCouponsCount")
  .post(fetchCoupons.getStaticDynamicCouponsCount);

module.exports = router;
